### ISSUE TITLE
Consider folding Makefile functions into the script

### ISSUE THREAD

**Issue by scottyeager** [Mik-TF/flist_cli#1]
For the purposes here, `make` is being used essentially as a script with multiple commands. Since the project is also a script with multiple commands, I think it makes sense to just have the `make` actions be additional commands on the script.

Then install can just look like this:

```
git clone ...
cd ...
sudo bash flist.sh install
```

Later uninstall can just be:

```
sudo flist uninstall
```

**Comment by mik-tf** [comment]
This makes sense as users can delete the repo and lose the make access, while using the script, they can uninstall anywhere/anytime.

Will make a PR. Thanks!

**Comment by mik-tf** [comment]
Amazing suggestion. Thanks!
