### ISSUE TITLE
Remove suggestion to export TOKEN

### ISSUE THREAD

**Issue by scottyeager** [Mik-TF/flist_cli#4]
After logging in, this message is printed:

https://github.com/Mik-TF/flist_cli/blob/1dba0d1ffb13f93f4ce2b9c7acf87acc5e8fd780/flist.sh#L29-L30

But actually the script is reading the token from the file itself, which is really the better option. I'd remove this suggestion to export a variable into every shell session. It's not actually being used and the outcome is potentially harmful (polluting the global namespace with a fairly generic variable name).

**Comment by mik-tf** [comment]
Excellent remark. Done.
